/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.simulation.system;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;



/**
 *
 * @author User
 */
public class DashboardForm extends javax.swing.JFrame {
   
    private ATM atm;
    private Account account;
    private FileManager fileManager;
  
    /**
     * Creates new form Dashboard
     */
    public DashboardForm(ATM atm, Account account, FileManager fileManager) {
        initComponents();
        
        this.atm = atm;
        this.account = account;
        this.fileManager = fileManager;
        
        setLocationRelativeTo(null);
        setResizable(false);
        showDate();
        showTime();
        
        
        
        lblBalance.setText(
        "Tk " + String.format("%.2f", account.getBalance())
     );
  
   }
    
    private void showLoading() {

    lblLoading.setText("Loading...");

    lblLoading.setVisible(true);

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {
        lblLoading.setText("");
        lblLoading.setVisible(false);
    });

    timer.setRepeats(false);
    timer.start();
}
    
 
   
     private void showDate() {

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

        lblDate.setText(sdf.format(new Date()));

}
         
   private void showTime() {

    Timer timer = new Timer(1000, new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {

            SimpleDateFormat sdf =
                    new SimpleDateFormat("hh:mm:ss a");

            lblTime.setText(sdf.format(new Date()));

        }

    });

    timer.start();

}      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        pnlButtons = new javax.swing.JPanel();
        btnDeposit = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnCheckBalance = new javax.swing.JButton();
        btnFastCash = new javax.swing.JButton();
        btnChangePin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnTransactionHistory = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblATMTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlBalance = new javax.swing.JPanel();
        lblBalanceTitle = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlButtons.setBackground(new java.awt.Color(102, 102, 102));

        btnDeposit.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-deposit-20.png")); // NOI18N
        btnDeposit.setText("Deposit");
        btnDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepositMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDepositMouseExited(evt);
            }
        });
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnWithdraw.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-money-bag-20.png")); // NOI18N
        btnWithdraw.setText("Withdraw");
        btnWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnWithdrawMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWithdrawMouseExited(evt);
            }
        });
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnCheckBalance.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-check-dollar-20.png")); // NOI18N
        btnCheckBalance.setText("Check Balance");
        btnCheckBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckBalanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckBalanceMouseExited(evt);
            }
        });
        btnCheckBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckBalanceActionPerformed(evt);
            }
        });

        btnFastCash.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-flash-20.png")); // NOI18N
        btnFastCash.setText("Fast Cash");
        btnFastCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFastCashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFastCashMouseExited(evt);
            }
        });
        btnFastCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFastCashActionPerformed(evt);
            }
        });

        btnChangePin.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-change-20.png")); // NOI18N
        btnChangePin.setText("Change PIN");
        btnChangePin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChangePinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangePinMouseExited(evt);
            }
        });
        btnChangePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePinActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-logout-20.png")); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnTransactionHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-history-folder-20.png")); // NOI18N
        btnTransactionHistory.setText("Transaction History");
        btnTransactionHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransactionHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransactionHistoryMouseExited(evt);
            }
        });
        btnTransactionHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btnFastCash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChangePin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheckBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFastCash, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblATMTitle.setBackground(new java.awt.Color(204, 204, 204));
        lblATMTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblATMTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblATMTitle.setText("DIGITAL ATM");

        lblDate.setForeground(new java.awt.Color(255, 0, 0));
        lblDate.setText("Date");

        lblTime.setForeground(new java.awt.Color(204, 0, 0));
        lblTime.setText("Time");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-atm-20.png")); // NOI18N

        lblSubtitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(0, 102, 102));
        lblSubtitle.setText("Secure Banking System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblATMTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSubtitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblATMTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlBalance.setBackground(new java.awt.Color(153, 153, 153));

        lblBalanceTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBalanceTitle.setForeground(new java.awt.Color(0, 0, 255));
        lblBalanceTitle.setText("CURRENT BALANCE");

        lblBalance.setBackground(new java.awt.Color(204, 204, 204));
        lblBalance.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlBalanceLayout = new javax.swing.GroupLayout(pnlBalance);
        pnlBalance.setLayout(pnlBalanceLayout);
        pnlBalanceLayout.setHorizontalGroup(
            pnlBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBalanceLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblBalanceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(pnlBalanceLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBalanceLayout.setVerticalGroup(
            pnlBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBalanceLayout.createSequentialGroup()
                .addComponent(lblBalanceTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblLoading.setBackground(new java.awt.Color(255, 255, 255));
        lblLoading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(pnlBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoading, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
         showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {

        DepositForm deposit =
                new DepositForm(atm, account, fileManager);

        deposit.setVisible(true);

        this.dispose();
    });

    timer.setRepeats(false);
    timer.start();
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnCheckBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckBalanceActionPerformed
        // TODO add your handling code here:
          showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {

        BalanceForm balance =
                new BalanceForm(atm, account, fileManager);

        balance.setVisible(true);
        this.dispose();
    });

    timer.setRepeats(false);
    timer.start();

    }//GEN-LAST:event_btnCheckBalanceActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
        showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {

        WithdrawForm withdraw =
                new WithdrawForm(atm, account, fileManager);

        withdraw.setVisible(true);
        this.dispose();
    });

    timer.setRepeats(false);
    timer.start();
        
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnChangePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePinActionPerformed
        // TODO add your handling code here:
          showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {

        ChangePINForm pin =
                new ChangePINForm(atm, account, fileManager);

        pin.setVisible(true);
        this.dispose();
    });

    timer.setRepeats(false);
    timer.start();
    }//GEN-LAST:event_btnChangePinActionPerformed

    private void btnFastCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFastCashActionPerformed
        // TODO add your handling code here:
        showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {

        FastCashForm fastCash =
                new FastCashForm(atm, account, fileManager);

        fastCash.setVisible(true);

        this.dispose();
    });

    timer.setRepeats(false);
    timer.start();

    }//GEN-LAST:event_btnFastCashActionPerformed

    private void btnTransactionHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionHistoryActionPerformed
        // TODO add your handling code here:
         
    showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {

        TransactionHistoryForm history =
                new TransactionHistoryForm(atm, account, fileManager);

        history.setVisible(true);
        this.dispose();
    });

    timer.setRepeats(false);
    timer.start();

    this.dispose();
    }//GEN-LAST:event_btnTransactionHistoryActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
          int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to exit?",
            "Exit",
            JOptionPane.YES_NO_OPTION);

    if (choice == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDepositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositMouseEntered
        // TODO add your handling code here:
       btnDeposit.setBackground(new java.awt.Color(0, 255, 0));
    btnDeposit.setForeground(java.awt.Color.WHITE);

    btnDeposit.setCursor(
        new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)
    );
        
    }//GEN-LAST:event_btnDepositMouseEntered

    private void btnDepositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositMouseExited
        // TODO add your handling code here:
           btnDeposit.setBackground(new java.awt.Color(240, 240, 240));
    btnDeposit.setForeground(java.awt.Color.BLACK);

    btnDeposit.setCursor(
        new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)
    );
    }//GEN-LAST:event_btnDepositMouseExited

    private void btnWithdrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWithdrawMouseEntered
        // TODO add your handling code here:
         btnWithdraw.setBackground(new java.awt.Color(0, 150, 220));
    btnWithdraw.setForeground(java.awt.Color.WHITE);
    btnWithdraw.setCursor(
        new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)
    );
    }//GEN-LAST:event_btnWithdrawMouseEntered

    private void btnWithdrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWithdrawMouseExited
        // TODO add your handling code here:
        btnWithdraw.setBackground(java.awt.Color.WHITE);
    btnWithdraw.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnWithdrawMouseExited

    private void btnFastCashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastCashMouseEntered
        // TODO add your handling code here:
        
    btnFastCash.setBackground(new java.awt.Color(255, 180, 0));
    btnFastCash.setForeground(java.awt.Color.WHITE);
    btnFastCash.setCursor(
        new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)
    );
    
    }//GEN-LAST:event_btnFastCashMouseEntered

    private void btnFastCashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastCashMouseExited
        // TODO add your handling code here:
        
    btnFastCash.setBackground(java.awt.Color.WHITE);
    btnFastCash.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnFastCashMouseExited

    private void btnCheckBalanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckBalanceMouseEntered
        // TODO add your handling code here:
        btnCheckBalance.setBackground(new java.awt.Color(120, 80, 200));
    btnCheckBalance.setForeground(java.awt.Color.WHITE);
    btnCheckBalance.setCursor(
        new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)
    );
    }//GEN-LAST:event_btnCheckBalanceMouseEntered

    private void btnCheckBalanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckBalanceMouseExited
        // TODO add your handling code here:
         btnCheckBalance.setBackground(java.awt.Color.WHITE);
    btnCheckBalance.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnCheckBalanceMouseExited

    private void btnTransactionHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransactionHistoryMouseEntered
        // TODO add your handling code here:
         btnTransactionHistory.setBackground(
        new java.awt.Color(0, 150, 200)
    );

    btnTransactionHistory.setForeground(
        java.awt.Color.WHITE
    );

    btnTransactionHistory.setCursor(
        new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)
    );
    }//GEN-LAST:event_btnTransactionHistoryMouseEntered

    private void btnTransactionHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransactionHistoryMouseExited
        // TODO add your handling code here:
         btnTransactionHistory.setBackground(java.awt.Color.WHITE);
    btnTransactionHistory.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnTransactionHistoryMouseExited

    private void btnChangePinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePinMouseEntered
        // TODO add your handling code here:
         btnChangePin.setBackground(
        new java.awt.Color(150, 80, 200)
    );

    btnChangePin.setForeground(
        java.awt.Color.WHITE
    );

    btnChangePin.setCursor(
        new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)
    );
    }//GEN-LAST:event_btnChangePinMouseEntered

    private void btnChangePinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePinMouseExited
        // TODO add your handling code here:
        btnChangePin.setBackground(java.awt.Color.WHITE);
    btnChangePin.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnChangePinMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(new java.awt.Color(180, 0, 0));
    btnExit.setForeground(java.awt.Color.WHITE);

    btnExit.setCursor(
        new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)
    );
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        
    btnExit.setBackground(java.awt.Color.WHITE);
    btnExit.setForeground(java.awt.Color.BLACK);

    btnExit.setCursor(
        new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)
    );
    }//GEN-LAST:event_btnExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {

    Account account = new Account("1001", "Saikat", 1234, 5000);
    ATM atm = new ATM(account);
    FileManager fileManager = new FileManager();

    new DashboardForm(atm, account, fileManager).setVisible(true);
}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePin;
    private javax.swing.JButton btnCheckBalance;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFastCash;
    private javax.swing.JButton btnTransactionHistory;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblATMTitle;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalanceTitle;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlBalance;
    private javax.swing.JPanel pnlButtons;
    // End of variables declaration//GEN-END:variables
}
