/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.simulation.system;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author User
 */
public class FastCashForm extends javax.swing.JFrame {

    private ATM atm;
private Account account;
private FileManager fileManager;
    /**
     * Creates new form FastCashForm
     */
    public FastCashForm(ATM atm, Account account, FileManager fileManager) {
        
        initComponents();
        
    this.atm = atm;
    this.account = account;
    this.fileManager = fileManager;

    setLocationRelativeTo(null);
    setResizable(false);
    
    }
    private void showLoading() {

    lblLoading.setText("Loading...");
    lblLoading.setVisible(true);

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {

        lblLoading.setText("");
        lblLoading.setVisible(false);

    });

    timer.setRepeats(false);
    timer.start();
}
    
    private void fastCashWithdraw(double amount) {

    // Minimum withdrawal
    if (amount < 500) {

        JOptionPane.showMessageDialog(
                this,
                "Minimum withdrawal amount is Tk 500."
        );

        return;
    }

    // Maximum withdrawal
    if (amount > 20000) {

        JOptionPane.showMessageDialog(
                this,
                "Maximum withdrawal amount is Tk 20,000."
        );

        return;
    }

    // Balance check
    if (amount > account.getBalance()) {

        JOptionPane.showMessageDialog(
                this,
                "Insufficient Balance!"
        );

        return;
    }

    // Withdraw money
    atm.withdraw(amount);

    // Save updated account
    fileManager.saveAccount(account);

    // Save transaction history
    DateTimeFormatter dtf =
            DateTimeFormatter.ofPattern("dd-MM-yyyy hh:mm a");

    String history = String.format(
        "%-22s %-12s Tk %.2f%n",
        dtf.format(LocalDateTime.now()),
        "Fast Cash",
        amount
  );

    fileManager.saveHistory(history);

    JOptionPane.showMessageDialog(
        this,
        "TRANSACTION SUCCESSFUL\n\n"
        + "Please collect your cash.\n\n"
        + "Amount: Tk " + amount,
        "ATM - Transaction Successful",
        JOptionPane.INFORMATION_MESSAGE
);
}
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn500 = new javax.swing.JButton();
        btn1000 = new javax.swing.JButton();
        btn10000 = new javax.swing.JButton();
        btn5000 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btn2000 = new javax.swing.JButton();
        btn20000 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Fast Cash");

        btn500.setBackground(new java.awt.Color(204, 255, 204));
        btn500.setText("500 TK");
        btn500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn500MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn500MouseExited(evt);
            }
        });
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });

        btn1000.setBackground(new java.awt.Color(204, 255, 204));
        btn1000.setText("1000 TK");
        btn1000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1000MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1000MouseExited(evt);
            }
        });
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });

        btn10000.setBackground(new java.awt.Color(204, 255, 204));
        btn10000.setText("10000 TK");
        btn10000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn10000MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn10000MouseExited(evt);
            }
        });
        btn10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10000ActionPerformed(evt);
            }
        });

        btn5000.setBackground(new java.awt.Color(204, 255, 204));
        btn5000.setText("5000 TK");
        btn5000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5000MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5000MouseExited(evt);
            }
        });
        btn5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5000ActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 0, 0));
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btn2000.setText("2000 TK");
        btn2000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2000MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2000MouseExited(evt);
            }
        });
        btn2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2000ActionPerformed(evt);
            }
        });

        btn20000.setText("20000 TK");
        btn20000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn20000MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn20000MouseExited(evt);
            }
        });
        btn20000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20000ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn500, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2000, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn10000))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn1000, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5000, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn20000, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1000)
                    .addComponent(btn500))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5000)
                    .addComponent(btn2000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn20000)
                    .addComponent(btn10000))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("DIGITAL ATM");

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Secure Banking System");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icons8-atm-20.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(63, 63, 63))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        lblLoading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoading, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        // TODO add your handling code here:

          showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {
        fastCashWithdraw(500);
    });

    timer.setRepeats(false);
    timer.start();

    
    }//GEN-LAST:event_btn500ActionPerformed

    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        // TODO add your handling code here:
       
   
      showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {
        fastCashWithdraw(1000);
    });

    timer.setRepeats(false);
    timer.start();
    }//GEN-LAST:event_btn1000ActionPerformed

    private void btn10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10000ActionPerformed
        // TODO add your handling code here:
     
     
    
    showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {
        fastCashWithdraw(10000);
    });

    timer.setRepeats(false);
    timer.start();
    }//GEN-LAST:event_btn10000ActionPerformed

    private void btn5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5000ActionPerformed
        // TODO add your handling code here:
    
    
     showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {
        fastCashWithdraw(5000);
    });

    timer.setRepeats(false);
    timer.start();
    }//GEN-LAST:event_btn5000ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        DashboardForm dashboard = new DashboardForm(atm, account, fileManager);

    dashboard.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btn2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2000ActionPerformed
        // TODO add your handling code here:
        
            showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {
        fastCashWithdraw(2000);
    });

    timer.setRepeats(false);
    timer.start();
    }//GEN-LAST:event_btn2000ActionPerformed

    private void btn20000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20000ActionPerformed
        // TODO add your handling code here:
         
          showLoading();

    javax.swing.Timer timer = new javax.swing.Timer(800, e -> {
        fastCashWithdraw(20000);
    });

    timer.setRepeats(false);
    timer.start();
    }//GEN-LAST:event_btn20000ActionPerformed

    private void btn500MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn500MouseEntered
        // TODO add your handling code here:
          btn500.setBackground(new java.awt.Color(0, 180, 100));
          btn500.setForeground(java.awt.Color.WHITE);
          btn500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn500MouseEntered

    private void btn500MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn500MouseExited
        // TODO add your handling code here:
          btn500.setBackground(new java.awt.Color(204, 255, 204));
    btn500.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btn500MouseExited

    private void btn1000MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1000MouseEntered
        // TODO add your handling code here:
        btn1000.setBackground(new java.awt.Color(0, 180, 100));
    btn1000.setForeground(java.awt.Color.WHITE);
    btn1000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn1000MouseEntered

    private void btn1000MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1000MouseExited
        // TODO add your handling code here:
         btn1000.setBackground(new java.awt.Color(204, 255, 204));
    btn1000.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btn1000MouseExited

    private void btn2000MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2000MouseEntered
        // TODO add your handling code here:
        btn2000.setBackground(new java.awt.Color(0, 180, 100));
    btn2000.setForeground(java.awt.Color.WHITE);
    btn2000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn2000MouseEntered

    private void btn2000MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2000MouseExited
        // TODO add your handling code here:
        btn2000.setBackground(new java.awt.Color(204, 255, 204));
    btn2000.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btn2000MouseExited

    private void btn5000MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5000MouseEntered
        // TODO add your handling code here:
        btn5000.setBackground(new java.awt.Color(0, 180, 100));
    btn5000.setForeground(java.awt.Color.WHITE);
    btn5000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn5000MouseEntered

    private void btn5000MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5000MouseExited
        // TODO add your handling code here:
         btn5000.setBackground(new java.awt.Color(204, 255, 204));
    btn5000.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btn5000MouseExited

    private void btn10000MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10000MouseEntered
        // TODO add your handling code here:
        btn10000.setBackground(new java.awt.Color(0, 180, 100));
    btn10000.setForeground(java.awt.Color.WHITE);
    btn10000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn10000MouseEntered

    private void btn10000MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10000MouseExited
        // TODO add your handling code here:
         btn10000.setBackground(new java.awt.Color(204, 255, 204));
    btn10000.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btn10000MouseExited

    private void btn20000MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn20000MouseEntered
        // TODO add your handling code here:
         btn20000.setBackground(new java.awt.Color(0, 180, 100));
    btn20000.setForeground(java.awt.Color.WHITE);
    btn20000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn20000MouseEntered

    private void btn20000MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn20000MouseExited
        // TODO add your handling code here:
         btn20000.setBackground(new java.awt.Color(204, 255, 204));
    btn20000.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btn20000MouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
            btnBack.setBackground(new java.awt.Color(180, 0, 0));
    btnBack.setForeground(java.awt.Color.WHITE);
    btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
         btnBack.setBackground(new java.awt.Color(255, 0, 0));
    btnBack.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_btnBackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Account account = new Account("1001", "Saikat", 1234, 8000);
        ATM atm = new ATM(account);
        FileManager fileManager = new FileManager();

        new FastCashForm(atm, account, fileManager).setVisible(true);
    }
  });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1000;
    private javax.swing.JButton btn10000;
    private javax.swing.JButton btn2000;
    private javax.swing.JButton btn20000;
    private javax.swing.JButton btn500;
    private javax.swing.JButton btn5000;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLoading;
    // End of variables declaration//GEN-END:variables
}
