/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.simulation.system;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author User
 */
public class WithdrawForm extends javax.swing.JFrame {

    private ATM atm;
private Account account;
private FileManager fileManager;

    /**
     * Creates new form WithdrawForm
     */
    public WithdrawForm(ATM atm, Account account, FileManager fileManager) {
        initComponents();
        
         this.atm = atm;
         this.account = account;
         this.fileManager = fileManager;
         
    setSize(500, 350);
    setLocationRelativeTo(null);
    setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Withdraw Money");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Amount  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 20));

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 30));

        btnBack.setBackground(new java.awt.Color(255, 0, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, -1));

        btnWithdraw.setBackground(new java.awt.Color(0, 255, 51));
        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });
        getContentPane().add(btnWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
       
  try {

        double amount = Double.parseDouble(txtAmount.getText());
        
        if (amount < 500) {

    JOptionPane.showMessageDialog(this,
            "Minimum withdrawal amount is ৳500.");

    txtAmount.setText("");
    txtAmount.requestFocus();

    return;
}

if (amount % 500 != 0) {

    JOptionPane.showMessageDialog(this,
            "Please enter an amount in multiples of ৳500.");

    txtAmount.setText("");
    txtAmount.requestFocus();

    return;
}

        if (amount <= 0) {

            JOptionPane.showMessageDialog(this,
                    "Please enter a valid amount.");

            txtAmount.requestFocus();
            return;
        }
        
        if (amount > 20000) {

    JOptionPane.showMessageDialog(this,
            "Maximum withdrawal limit is ৳20,000 per transaction.");

    txtAmount.setText("");
    txtAmount.requestFocus();

    return;
}

        if (amount > account.getBalance()) {

            JOptionPane.showMessageDialog(this,
                    "Insufficient Balance!");

            txtAmount.setText("");
            txtAmount.requestFocus();
            return;
        }

        atm.withdraw(amount);

        fileManager.saveAccount(account);
        
        DateTimeFormatter dtf =
        DateTimeFormatter.ofPattern("dd-MM-yyyy hh:mm a");

String history =
        dtf.format(LocalDateTime.now())
        + "   Withdraw   ৳" + amount + "\n";

fileManager.saveHistory(history);

        JOptionPane.showMessageDialog(this,
                "Withdraw Successful!");

        txtAmount.setText("");

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Please enter numbers only.");

        txtAmount.setText("");
        txtAmount.requestFocus();
    }



    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        DashboardForm dashboard = new DashboardForm(atm, account, fileManager);
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {

        Account account = new Account("1001", "Saikat", 1234, 5000);
        ATM atm = new ATM(account);
        FileManager fileManager = new FileManager();

        new WithdrawForm(atm, account, fileManager).setVisible(true);
    }
  });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
